################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/competitionscreen_screen/CompetitionScreenPresenter.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/competitionscreen_screen/CompetitionScreenView.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/driverscreen_screen/DriverScreenPresenter.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/driverscreen_screen/DriverScreenView.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/common/FrontendApplication.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/maininfotaiment_screen/MainInfotaimentPresenter.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/maininfotaiment_screen/MainInfotaimentView.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/missionselect_screen/MissionSelectPresenter.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/missionselect_screen/MissionSelectView.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/model/Model.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/startup_screen/StartupPresenter.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/startup_screen/StartupView.cpp \
C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/containers/missionBtnContainer.cpp 

OBJS += \
./Application/User/gui/CompetitionScreenPresenter.o \
./Application/User/gui/CompetitionScreenView.o \
./Application/User/gui/DriverScreenPresenter.o \
./Application/User/gui/DriverScreenView.o \
./Application/User/gui/FrontendApplication.o \
./Application/User/gui/MainInfotaimentPresenter.o \
./Application/User/gui/MainInfotaimentView.o \
./Application/User/gui/MissionSelectPresenter.o \
./Application/User/gui/MissionSelectView.o \
./Application/User/gui/Model.o \
./Application/User/gui/StartupPresenter.o \
./Application/User/gui/StartupView.o \
./Application/User/gui/missionBtnContainer.o 

CPP_DEPS += \
./Application/User/gui/CompetitionScreenPresenter.d \
./Application/User/gui/CompetitionScreenView.d \
./Application/User/gui/DriverScreenPresenter.d \
./Application/User/gui/DriverScreenView.d \
./Application/User/gui/FrontendApplication.d \
./Application/User/gui/MainInfotaimentPresenter.d \
./Application/User/gui/MainInfotaimentView.d \
./Application/User/gui/MissionSelectPresenter.d \
./Application/User/gui/MissionSelectView.d \
./Application/User/gui/Model.d \
./Application/User/gui/StartupPresenter.d \
./Application/User/gui/StartupView.d \
./Application/User/gui/missionBtnContainer.d 


# Each subdirectory must supply rules for building sources it contributes
Application/User/gui/CompetitionScreenPresenter.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/competitionscreen_screen/CompetitionScreenPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/CompetitionScreenView.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/competitionscreen_screen/CompetitionScreenView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/DriverScreenPresenter.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/driverscreen_screen/DriverScreenPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/DriverScreenView.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/driverscreen_screen/DriverScreenView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/FrontendApplication.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/common/FrontendApplication.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/MainInfotaimentPresenter.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/maininfotaiment_screen/MainInfotaimentPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/MainInfotaimentView.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/maininfotaiment_screen/MainInfotaimentView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/MissionSelectPresenter.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/missionselect_screen/MissionSelectPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/MissionSelectView.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/missionselect_screen/MissionSelectView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/Model.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/model/Model.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/StartupPresenter.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/startup_screen/StartupPresenter.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/StartupView.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/startup_screen/StartupView.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/gui/missionBtnContainer.o: C:/Users/Enrico/Formula/FirstInfotainmentAU1/TouchGFX/gui/src/containers/missionBtnContainer.cpp Application/User/gui/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DSTM32F469xx -DUSE_BPP=16 -DDEBUG -c -I../../Core/Inc -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/back/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/brake/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/core/net/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/buffer" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/can/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/filter/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/gpio/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/timing/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/lib/util/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/mmr_core/app/stm/inc" -I"C:/Users/Enrico/Formula/FirstInfotainmentAU1/Shared/inc" -I../../Drivers/CMSIS/Include -I../../TouchGFX/target -I../../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../../TouchGFX/App -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../TouchGFX/target/generated -I../../Drivers/BSP/Components/Common -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/BSP/STM32469I-Discovery -I../../Drivers/STM32F4xx_HAL_Driver/Inc -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../TouchGFX/generated/videos/include -Os -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -femit-class-debug-always -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-gui

clean-Application-2f-User-2f-gui:
	-$(RM) ./Application/User/gui/CompetitionScreenPresenter.cyclo ./Application/User/gui/CompetitionScreenPresenter.d ./Application/User/gui/CompetitionScreenPresenter.o ./Application/User/gui/CompetitionScreenPresenter.su ./Application/User/gui/CompetitionScreenView.cyclo ./Application/User/gui/CompetitionScreenView.d ./Application/User/gui/CompetitionScreenView.o ./Application/User/gui/CompetitionScreenView.su ./Application/User/gui/DriverScreenPresenter.cyclo ./Application/User/gui/DriverScreenPresenter.d ./Application/User/gui/DriverScreenPresenter.o ./Application/User/gui/DriverScreenPresenter.su ./Application/User/gui/DriverScreenView.cyclo ./Application/User/gui/DriverScreenView.d ./Application/User/gui/DriverScreenView.o ./Application/User/gui/DriverScreenView.su ./Application/User/gui/FrontendApplication.cyclo ./Application/User/gui/FrontendApplication.d ./Application/User/gui/FrontendApplication.o ./Application/User/gui/FrontendApplication.su ./Application/User/gui/MainInfotaimentPresenter.cyclo ./Application/User/gui/MainInfotaimentPresenter.d ./Application/User/gui/MainInfotaimentPresenter.o ./Application/User/gui/MainInfotaimentPresenter.su ./Application/User/gui/MainInfotaimentView.cyclo ./Application/User/gui/MainInfotaimentView.d ./Application/User/gui/MainInfotaimentView.o ./Application/User/gui/MainInfotaimentView.su ./Application/User/gui/MissionSelectPresenter.cyclo ./Application/User/gui/MissionSelectPresenter.d ./Application/User/gui/MissionSelectPresenter.o ./Application/User/gui/MissionSelectPresenter.su ./Application/User/gui/MissionSelectView.cyclo ./Application/User/gui/MissionSelectView.d ./Application/User/gui/MissionSelectView.o ./Application/User/gui/MissionSelectView.su ./Application/User/gui/Model.cyclo ./Application/User/gui/Model.d ./Application/User/gui/Model.o ./Application/User/gui/Model.su ./Application/User/gui/StartupPresenter.cyclo ./Application/User/gui/StartupPresenter.d ./Application/User/gui/StartupPresenter.o ./Application/User/gui/StartupPresenter.su ./Application/User/gui/StartupView.cyclo ./Application/User/gui/StartupView.d ./Application/User/gui/StartupView.o ./Application/User/gui/StartupView.su ./Application/User/gui/missionBtnContainer.cyclo ./Application/User/gui/missionBtnContainer.d ./Application/User/gui/missionBtnContainer.o ./Application/User/gui/missionBtnContainer.su

.PHONY: clean-Application-2f-User-2f-gui

